apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: bestie-route
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: bestie-service
    weight: 100
  wildcardPolicy: None
