# permissions for end users to edit besties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bestie-editor-role
rules:
- apiGroups:
  - pets.bestie.com
  resources:
  - besties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pets.bestie.com
  resources:
  - besties/status
  verbs:
  - get
