
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pets.bestie.com
  resources:
  - besties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pets.bestie.com
  resources:
  - besties/finalizers
  verbs:
  - update
- apiGroups:
  - pets.bestie.com
  resources:
  - besties/status
  verbs:
  - get
  - patch
  - update
